
class KEYS:
    WF = "NOVON_WORKFLOW"
    DB_BUILDER_RAN = "DB_BUILDER_RAN"
    LUMI_SELECTION = "LUMI_SELECTION"
    IES_SELECTION = "IES_SELECTION"
    IES_DOWN_NORM = "IES_DOWN_NORM"
    IES_UP_NORM = "IES_UP_NORM"
    MERGED_IES_PER_SCENE = "MERGED_IES_PER_SCENE"
    SCENE_SELECTIONS = "SCENE_SELECTIONS"
    LENGTH_TABLE = "LENGTH_TABLE"
    LENGTH_TABLE_LOCKED = "LENGTH_TABLE_LOCKED"
    BATCH_PLAN = "BATCH_PLAN"

